name: Trivy IaC Scan

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s)_$(uname -m).tar.gz
          tar zxvf trivy_$(uname -s)_$(uname -m).tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      - name: Scan IaC files with Trivy
        run: |
          trivy config dev
